### PR TITLE
Fixes #13

### LINKED ISSUE #13: Include HTTP-Verb in Output
Hi there,
just installed you package and really like the output so far. But i would be cool if you could include the HTTP Verb (if specified) for a route.

Just a small improvement proposal. :)

Best regards
Sven

### PR DESCRIPTION
**Pull request by nicolaspierre1990**
Added HTTP verb with the output. Default is GET

### CODE REVIEW

**Comment by kobake** [comment]
@nicolaspierre1990 
Thank you very much for your contribute! And I apoligize for my slow review action... 😢 

As @ghandmann say (#13), verb is important information. I agree it.

Your fix is very great, but I found some problem (especially non-enough using directive) and I added fixing commits to this branch.

After adding my commits, I confirmed this PR has no problem. I just merge it.

## before this PR
capt_20181216_171456_00

## after this PR
capt_20181216_170021_00

**Comment by nicolaspierre1990** [comment]
No problem, can you also update the nuget package ? :-D

**Comment by kobake** [comment]
Sure. I just now uploaded new package v0.5.2. 
Current status of new package v0.5.2 in NuGet Garally is `Validating`. It will be officially published soon I think.

- https://www.nuget.org/packages/AspNetCore.RouteAnalyzer

**Comment by kobake** [comment]
sorry, I mistaked to make v0.5.2 package. I'll retry soon 😭

**Comment by kobake** [comment]
I just uploaded v0.5.3 instead!!

**Comment by kobake** [comment]
done 👍

**Pull request merged**
